### ISSUE TITLE
What code smells should we add?

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/html-css-overview#11]
Early CSS examples for the game project show that some developers are using numbers in their class names, and copying styles between them.

I don't think any changes need to be made, other than an emphasis on DRY in CSS, but @MattB-GA-Boston may have more information.

**Comment by laurenfazah** [comment]
I created a new attributes table to draw emphasis on `class`, `id`, and `data-*`. Really hoping to drill down what's used where, when and why to avoid these smells.

**Comment by jrhorn424** [comment]
@ga-wdi-boston/core Should we include a list of code smells and best practices in this lesson?

**Comment by jrhorn424** [comment]
Closed in favor of #2
