### ISSUE TITLE
Structure lesson to use WebPack tooling.

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/html-css-overview#12]
See https://github.com/ga-wdi-boston/planning/issues/5
(Formerly https://github.com/ga-wdi-boston/010/issues/4)

**Comment by RealWeeks** [comment]
@RDegnen ref @gaand or @jrhorn424 if they want to stick to this.

**Comment by gaand** [comment]
@RDegnen @J-Weeks Yes, we want to do this.  Everything should be based on one of the templates.

**Comment by RDegnen** [comment]
I integrated webpack in

**Comment by gaand** [comment]
@RDegnen For issue you didn't open, out policy is to `@` the person who did open the issue (or the person who asked them to open it) and say you believe it should be closed.  This is to ensure that issues go through an appropriate life cycle.  @MattB-GA-Boston I'm leaving this closed, but please reopen if you have any concerns.
