### ISSUE TITLE
Consider adding forms

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/html-css-overview#16]
Is there a way we can show forms here along with other html elements to show that html is larger than what we show them

**Comment by gaand** [comment]
I don't see forms in the pull that closed this issue so I'm concerned about information loss.

**Comment by berziiii** [comment]
I'm second guessing if this is needed here. Since we show them forms and how we use them with ajax/auth. Thoughts @gaand and @jrhorn424?

**Comment by jrhorn424** [comment]
I'm ambivalent. I'm ok with closing this @berziiii.

**Comment by jrhorn424** [comment]
Actually @berziiii ended up doing this during his lesson. We need best practices (#2), including _always_ wrapping `<input>`s in a `<form>`.
