### ISSUE TITLE
Reformat [fork and clone] holding the hyperlink and add a "(instructions)"

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/html-css-overview#18]
Can we reformat repos from this:
   [Fork and Clone](https://github.com/ga-wdi-boston/meta/wiki/ForkAndClone) this repository

to something like this:
   Fork and Clone ([instructions](https://github.com/ga-wdi-boston/meta/wiki/ForkAndClone)) this repository

If we did it this way, I think developers would stop forking and cloning the stupid ForkAndClone repo...

**Comment by gaand** [comment]
I'm not sure your proposal corrects the issue, but I'm not opposed.  

However, this _requires_ that the `talk-template` be updated, and that all talk-template based repositories be updated, so perhaps we should chat before the change?

@ga-wdi-boston/core

**Comment by jrhorn424** [comment]
@gaand is correct. This change belongs in `talk-template`, which doesn't fit into our technology-specific repository refresh instructions. @ga-wdi-boston/core

**Comment by payne-chris-r** [comment]
Opened in talk template. Closing here.
