### ISSUE TITLE
Break deployment instructions into `gh-pages-deployment-guide`

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/html-css-overview#19]
@ga-wdi-boston/core Other candidates for names?

**Comment by laurenfazah** [comment]
Got it made with that name here: https://github.com/ga-wdi-boston/gh-pages-deployment-guide

**Comment by berziiii** [comment]
Seems to be addressed. Okay to close @laurenfazah?

**Comment by jrhorn424** [comment]
I'll close this since I opened the issue. If anyone disagrees, feel free to reopen with a comment.
